        <!-- Date Selection Modal -->
        <div id="dateModal" class="fixed inset-0 bg-black bg-opacity-50 hidden z-50 flex items-center justify-center p-4">
            <div class="bg-white rounded-2xl shadow-xl max-w-md w-full">
                <div class="p-6">
                    <!-- Header -->
                    <div class="flex justify-between items-center mb-6">
                        <div>
                            <h3 class="text-xl font-bold text-gray-900 mb-1">Pilih Tanggal</h3>
                            <p class="text-gray-500 text-sm">Tentukan tanggal keberangkatan Anda</p>
                        </div>
                        <button onclick="closeDateModal()" class="text-gray-400 hover:text-gray-600 transition duration-200 p-2 hover:bg-gray-100 rounded-full">
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                            </svg>
                        </button>
                    </div>
                    
                    <!-- Trip Type Options -->
                    <div class="mb-6">
                        <div class="flex space-x-3">
                            <button id="oneWayBtn" onclick="switchTripType('oneWay')" class="flex-1 py-3 px-4 text-center font-medium rounded-lg border border-gray-300 transition duration-200" style="background: linear-gradient(135deg, #187499 0%, #36AE7E 100%); color: white;">
                                Sekali jalan
                            </button>
                            <button id="roundTripBtn" onclick="switchTripType('roundTrip')" class="flex-1 py-3 px-4 text-center font-medium rounded-lg border border-gray-300 transition duration-200 text-gray-700 hover:bg-gray-50">
                                Pulang pergi
                            </button>
                        </div>
                    </div>
                    
                    <!-- Calendar -->
                    <div class="mb-6">
                        <!-- Month Navigation -->
                        <div class="flex justify-between items-center mb-4">
                            <button onclick="previousMonth()" class="p-1 hover:bg-gray-100 rounded transition duration-200">
                                <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                                </svg>
                            </button>
                            <h4 class="text-lg font-semibold text-gray-900" id="currentMonth">August 2025</h4>
                            <button onclick="nextMonth()" class="p-1 hover:bg-gray-100 rounded transition duration-200">
                                <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                                </svg>
                            </button>
                        </div>
                        
                        <!-- Day Headers -->
                        <div class="grid grid-cols-7 gap-1 mb-2">
                            <div class="text-center text-sm font-medium text-gray-500 py-2">Mo</div>
                            <div class="text-center text-sm font-medium text-gray-500 py-2">Tu</div>
                            <div class="text-center text-sm font-medium text-gray-500 py-2">We</div>
                            <div class="text-center text-sm font-medium text-gray-500 py-2">Th</div>
                            <div class="text-center text-sm font-medium text-gray-500 py-2">Fr</div>
                            <div class="text-center text-sm font-medium text-gray-500 py-2">Sa</div>
                            <div class="text-center text-sm font-medium text-gray-500 py-2">Su</div>
                        </div>
                        
                        <!-- Calendar Days -->
                        <div id="calendarDays" class="grid grid-cols-7 gap-1">
                            <!-- Calendar days will be generated by JavaScript -->
                        </div>
                    </div>
                    
                    <!-- Selected Dates Display -->
                    <div id="selectedDatesDisplay" class="mb-6 p-4 bg-gray-50 rounded-lg">
                        <div class="grid grid-cols-2 gap-4">
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Tanggal Keberangkatan</label>
                                <div id="departureDateDisplay" class="p-3 bg-white border border-gray-300 rounded-lg text-gray-500">
                                    Pilih tanggal keberangkatan
                                </div>
                            </div>
                            <div id="returnDateSection">
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Tanggal Pulang</label>
                                <div id="returnDateDisplay" class="p-3 bg-white border border-gray-300 rounded-lg text-gray-500">
                                    Pilih tanggal pulang
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Save Button -->
                    <div class="flex justify-end">
                        <button onclick="saveDate()" class="px-6 py-2 text-white rounded-lg font-medium transition duration-200 shadow-md hover:shadow-lg" style="background: linear-gradient(135deg, #187499 0%, #36AE7E 100%);">
                            Simpan
                        </button>
                    </div>
                </div>
            </div>
        </div>